export const imgPreview = {
  img1: "/jos/lisca0.jpg",
  img2: "/jos/lisca2.jpg",
  img3: "/jos/lisca3.jpg",
  img4: "/jos/lisca4.jpg",
  img5: "/jos/lisca5.jpg",
  img6: "/jos/lisca6.jpg",
  img7: "/jos/lisca7.jpg",
  img8: "/jos/lisca8.jpg",
  img9: "/jos/lisca9.jpg",
  img10: "/card/children.jpg",
  img11: "card/lisca1.png",
  img12: "/card/lisca12.png",
  img13: "/card/lisca21.png",
  img14: "/jos/lisca0.jpg",
  img15: "/jos/lisca0.jpg",
  img16: "/jos/lisca0.jpg",
  img17: "/jos/lisca0.jpg",
  img18: "/jos/lisca0.jpg",
};
