import type { Metadata } from "next";
import { Inter,  Comic_Neue, Ubuntu, Pacifico, Poppins, Indie_Flower } from "next/font/google";
import "./globals.css";
import { HeroHeader } from "@/components/Navigation";
import FooterSection from "@/components/Footer";

const geistInter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const geistPlaywrite = Indie_Flower({
  variable: "--font-playwrite",
  weight: ["400"],
  subsets:['latin']
});

const geistComic = Comic_Neue({
  variable: "--font-comic",
  weight: ['300', '400', '700'],
  subsets: ['latin']
})

const geistUbuntu = Ubuntu({
  variable: "--font-ubuntu",
  weight:['300', '400', '500', '700'],
  subsets: ['latin']
})

const geistPacifico = Pacifico({
  variable: "--font-pacifico",
  weight:['400'],
  subsets: ['latin']
})

const poppins = Poppins({
  weight:['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Lisca Family",
  description: "Generated by DreamerWebdev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistInter.variable} ${poppins.className} ${geistComic.variable} ${geistPlaywrite.variable} ${geistPacifico.variable} ${geistUbuntu} antialiased`}
        suppressHydrationWarning
      >
        <HeroHeader />
        <main className="">{children}</main>
        <FooterSection />
      </body>
    </html>
  );
}
